/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ContestantsRouteImport } from './routes/contestants'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteIdRouteImport } from './routes/vote.$id'
import { Route as ContestantsIdRouteImport } from './routes/contestants.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminContestantsRouteImport } from './routes/_authenticated/admin.contestants'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsRoute = ContestantsRouteImport.update({
  id: '/contestants',
  path: '/contestants',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteIdRoute = VoteIdRouteImport.update({
  id: '/vote/$id',
  path: '/vote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsIdRoute = ContestantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContestantsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContestantsRoute =
  AuthenticatedAdminContestantsRouteImport.update({
    id: '/contestants',
    path: '/contestants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contestants': typeof ContestantsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/contestants/$id': typeof ContestantsIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/contestants': typeof AuthenticatedAdminContestantsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contestants': typeof ContestantsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/contestants/$id': typeof ContestantsIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/contestants': typeof AuthenticatedAdminContestantsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contestants': typeof ContestantsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/contestants/$id': typeof ContestantsIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/contestants': typeof AuthenticatedAdminContestantsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contestants'
    | '/leaderboard'
    | '/admin'
    | '/contestants/$id'
    | '/vote/$id'
    | '/admin/analytics'
    | '/admin/contestants'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contestants'
    | '/leaderboard'
    | '/contestants/$id'
    | '/vote/$id'
    | '/admin/analytics'
    | '/admin/contestants'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contestants'
    | '/leaderboard'
    | '/_authenticated/admin'
    | '/contestants/$id'
    | '/vote/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/contestants'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContestantsRoute: typeof ContestantsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  VoteIdRoute: typeof VoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants': {
      id: '/contestants'
      path: '/contestants'
      fullPath: '/contestants'
      preLoaderRoute: typeof ContestantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$id': {
      id: '/vote/$id'
      path: '/vote/$id'
      fullPath: '/vote/$id'
      preLoaderRoute: typeof VoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/$id': {
      id: '/contestants/$id'
      path: '/$id'
      fullPath: '/contestants/$id'
      preLoaderRoute: typeof ContestantsIdRouteImport
      parentRoute: typeof ContestantsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contestants': {
      id: '/_authenticated/admin/contestants'
      path: '/contestants'
      fullPath: '/admin/contestants'
      preLoaderRoute: typeof AuthenticatedAdminContestantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminContestantsRoute: typeof AuthenticatedAdminContestantsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminContestantsRoute: AuthenticatedAdminContestantsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ContestantsRouteChildren {
  ContestantsIdRoute: typeof ContestantsIdRoute
}

const ContestantsRouteChildren: ContestantsRouteChildren = {
  ContestantsIdRoute: ContestantsIdRoute,
}

const ContestantsRouteWithChildren = ContestantsRoute._addFileChildren(
  ContestantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContestantsRoute: ContestantsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  VoteIdRoute: VoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
